version: "3"
services: 
  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile-nginx
    container_name: nginx-container-laravel
    ports:
      - 8000:80
    links:
      - php

  php:
    build: ./
    container_name: php817_fpm_laravel
    expose:
      - 9000
